# Generated by Django 3.0.5 on 2020-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200429_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'MANAGER'), (3, 'REGULAR')], default=3),
        ),
    ]
