# Generated by Django 3.0.5 on 2020-05-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_split_datetime_part2'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
            preserve_default=False,
        ),
    ]
